# frozen_string_literal: true

source "https://rubygems.org"

gem "puma"
gem "roda"
gem "pg"
gem "sequel"
gem "rodauth"
gem "jwt"
gem "bcrypt"
gem "rake"
gem "waterdrop"
gem "rackup"
gem "avro_turf"
gem "dotenv", groups: [:development, :test]
